### ISSUE TITLE
Combined selectors?

### ISSUE THREAD

**Issue by iest** [threepointone/glamor#124]
Lets say I have the following css:
```css
.f1 { font-size: 1rem };
.red { background: red };
.f1.red { font-size: 2rem};
```
and the following html: 
```html
<div class="f1 red">
  I'm red and 2em!
</div>
```

How do I replicate this in glamor?
