### ISSUE TITLE
chrome merge bug

### ISSUE THREAD

**Issue by jessehart** [threepointone/glamor#158]
http://codepen.io/hart/pen/QGJyKy?editors=0010

**expected**: font size is 50px
**actual**: font size is inherited

i also noticed this happens randomly with margin + padding: http://codepen.io/hart/pen/eBQJKe?editors=0010

**expected**: top padding is 50px
**actual**: top padding is 0

**Comment by ChristopherBiscardi** [comment]
This looks like a Chrome bug. It's easy to check by popping Firefox open. `font: inherit` is misplaced in Chrome. (newlines added by me)

Firefox.

```css
.css-uymlcm,[data-css-uymlcm]{
-moz-box-sizing:border-box;
box-sizing:border-box;
border-width:0;
border-style:solid;
margin:0;
padding:0;
font:inherit;
text-transform:inherit;
text-decoration:none;
font-size:50px;
margin-right:5px;
}
```

Chrome

```css
.css-uymlcm,[data-css-uymlcm]{
-moz-box-sizing:border-box;
box-sizing:border-box;
border-style:solid;
margin:0;
padding:0;
border-width:0;
text-transform:inherit;
text-decoration:none;
font-size:50px;
margin-right:5px;
font:inherit;
}
```
