### ISSUE TITLE
How to convert comma into glamor ?

### ISSUE THREAD

**Issue by azopyros** [threepointone/glamor#187]
Hello,

In css, I want this rules :
```css
.btn:hover, .btn:active {
  color: red;
}
```

In glamor, I wrote this : 
```javascript
const btn = css`
  &:hover, &:active {
    color: red;
  }
`;

<a href="#" {...btn}>Link</a> // <-- this is JSX
```

The result, in the page, is 
```css
.btn:hover:active {
  color: red;
}
```

Did you already have the problem ? I know you can duplicate the rule, but I want to do it in 1 rule.
Any advices ?

Thx :)
