### ISSUE TITLE
Is content:url() supported?

### ISSUE THREAD

**Issue by bvaughn** [threepointone/glamor#295]
Just noticed a small issue that I believe is a bug.

The following CSS:
```js
css={{
  ':after': {
    content: '" " url(images/some-image.png)'
  }
}}
```

Is incorrectly converted by Glamor (2.20.29) to:
```css
.css-foo:after {
  content: "url(images/some-image.png)";
}
```

When it should be:
```css
.css-foo:after {
  content: " " url(images/some-image.png)`;
}
```

Removing the `" "` prefix yields the same unexpected result:

The following CSS:
```js
css={{
  ':after': {
    content: 'url(images/some-image.png)'
  }
}}
```

Becomes:
```css
.css-foo:after {
  content: "url(images/some-image.png)";
}
```

Instead of:
```css
.css-foo:after {
  content: url(images/some-image.png)`;
}
```
