### ISSUE TITLE
Nested Properties

### ISSUE THREAD

**Issue by knpwrs** [threepointone/glamor#316]
Would there be any interested in a PR to support [SCSS-style nested properties](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Nested_Properties)?

Example from that page:

```scss
.funky {
  font: {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
}
```

Practically, for glamor, that would mean the following:

```js
{
  fontFamily: 'fantasy',
  fontSize: '30em',
  weight: 'bold',
}
```

Could be the following:
```js
{
  font: {
    family: 'fantasy',
    size: '30em',
    weight: 'bold',
  },
}
```

This works for `margin`, `border`, `padding`, etc. Basically any set of rules with a common prefix.
