### ISSUE TITLE
Possible to remove data attributes from css?

### ISSUE THREAD

**Issue by kirkstrobeck** [threepointone/glamor#335]
I would like to remove the data attributes, so this

```css
.css-1amtj6d,[data-css-1amtj6d]{padding:10px;}
```

becomes this

```css
.css-1amtj6d{padding:10px;}
```

---

- [ ] Is this possible? 
- [ ] How?
