### ISSUE TITLE
content property: empty string (" ") becomes "px"

### ISSUE THREAD

**Issue by sdgluck** [threepointone/glamor#350]
I am trying to create a keyframe animation that looks like this:

```js
const cursorBlinkAnim = keyframes({
  '0%': {content: '_'},
  '100%': {content: ' '}
})
```

But when compiled by glamor the CSS becomes:

```css
@keyframes animation_wzvti9{0%{content:_;}100%{content:px;}}
```

Using any alternative whitespace character has similar behaviour.

Just in case it's important, I am using `glamorous` too.

Any ideas?
