### ISSUE TITLE
Add autoprefixer support for ie10

### ISSUE THREAD

**Issue by otbe** [threepointone/glamor#81]
Hi @threepointone,

we are targeting IE10&11 in our current project. I assume your autoprefixer fork supports `flexbox` only for IE 11 upwards. 

To be more specific: the current flex standard uses `justify-content: space-between` but the old draft implemented in IE10 uses `-ms-flex-pack: justify`. 

Current result in IE10 / Desired result in IE11:

```
-ms-flex-pack: space-between;
```

Desired result in IE10:

```
-ms-flex-pack: justify;
```

Any chances to get this in or to workaround this issue?

See this issue for more information:
https://github.com/postcss/autoprefixer/issues/165#issuecomment-255714452

Thanks 👍

**Comment by threepointone** [comment]
this should be fixable, give me a day or so. I'll try to think of a workaround too.

**Comment by threepointone** [comment]
given 
```jsx
{ justifyContent: 'space-between' }
```
is this the expected css?
```css
.css-1178gq1,[data-css-1178gq1] {
  justify-content:space-between;
  -webkit-justify-content:space-between;
  -ms-flex-pack:justify;
  -webkit-box-pack:justify;
}
```
